import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'quick-start/intro',
      label: 'Quick Start',
    },
    {
      type: 'category',
      label: 'Abeeway Devices',
      link: {
        type: 'generated-index',
        description: 'Documentation by tracker model.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '01-devices',
        },
      ],
    },
    {
      type: 'doc',
      id: 'device-activation/intro',
      label: 'Device Activation',
    },
    {
      type: 'category',
      label: 'Payload Format',
      link: {
        type: 'generated-index',
        description: 'Message payload structure and examples.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '03-payload',
        },
      ],
    },
    {
      type: 'category',
      label: 'Application Integration',
      link: {
        type: 'generated-index',
        description: 'Network server and platform integrations.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '04-integration',
        },
      ],
    },
    {
      type: 'category',
      label: 'Device Configuration',
      link: {
        type: 'generated-index',
        description: 'Tracker configuration and tuning guidance.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '05-configuration',
        },
      ],
    },
    {
      type: 'category',
      label: 'Firmware Reference Guide',
      link: {
        type: 'generated-index',
        description: 'AT3 firmware reference documentation grouped by release.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '06-firmware-reference-guide',
        },
      ],
    },
  ],
};

export default sidebars;
